# Generated by Django 5.2.8 on 2025-11-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('ir1', models.IntegerField()),
                ('ir2', models.IntegerField()),
                ('piezo', models.IntegerField()),
                ('relay', models.BooleanField()),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceData',
        ),
    ]
