# Generated by Django 5.2.8 on 2025-11-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdata', '0002_vehicledata_delete_devicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='piezo',
            field=models.FloatField(default=0),
        ),
    ]
