# Generated by Django 5.2.8 on 2025-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdata', '0003_alter_vehicledata_piezo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledata',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
