# Generated by Django 5.2.8 on 2025-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdata', '0004_vehicledata_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir1', models.IntegerField(default=0)),
                ('ir2', models.IntegerField(default=0)),
                ('piezo', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('arduino_relay', models.BooleanField(default=False)),
                ('piezo_relay', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeMCUData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir1', models.IntegerField(default=0)),
                ('ir2', models.IntegerField(default=0)),
                ('nodemcu_relay', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleData',
        ),
    ]
