# Generated by Django 5.2.8 on 2025-12-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdata', '0005_arduinodata_nodemcudata_delete_vehicledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arduinodata',
            old_name='timestamp',
            new_name='server_receive_time',
        ),
        migrations.RenameField(
            model_name='nodemcudata',
            old_name='timestamp',
            new_name='server_receive_time',
        ),
        migrations.AddField(
            model_name='arduinodata',
            name='device_capture_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arduinodata',
            name='sensor_id',
            field=models.CharField(default='ARDU_01', max_length=10),
        ),
        migrations.AddField(
            model_name='nodemcudata',
            name='device_capture_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodemcudata',
            name='sensor_id',
            field=models.CharField(default='NMCU_01', max_length=10),
        ),
    ]
